FROM python:3.10
RUN pip install --upgrade pip
COPY ./requirements.txt .
RUN pip install -r requirements.txt
COPY ./doosma /app
WORKDIR /app
COPY ./entrypoint_production.sh /
ENTRYPOINT ["sh", "/entrypoint_awsgi.sh"]
